spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customercache?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL7Dialect
  cache:
    cache-names:
      - customer-id
      - customer-name