server:
  port: 8090
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
     
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycrudDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace     
#GET: http://localhost:8090/actuator/health
#GET: http://localhost:8090/actuator/beans
#GET: http://localhost:8090/actuator/threaddump
#GET: http://localhost:8090/actuator/heapdump
#GET: http://localhost:8090/actuator/matrics
#GET: http://localhost:8090/actuator/metrics/jvm.memory.max
#we can enable or disable certain endpoints
#we can even create our own actuato endpoints either  

#We can dynamically change our configurations
#We can dynamically change our Log levels
#We can change certain values one time or we can get values
#We can manupulate we can do anything with that.
#Like - let say, you have a service, in your service 
#you have few levels say, level1 to level5, and
#those level you have a threshold values.
#You should be able to read those threshold values
#and set those threshold values dynamically!
#So let see how we can do this... let's create a class called StageEdPoint       
