server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zimrancis/spring-cloud-config-store  
          search-paths:
          - '*service'
          #uri: https://github.com/zimrancis/microservices-config-store  
          #search-paths:
          #- 'service-config/*service'
          #repos:            
          #username: root
          #passphrase: 12345
